### ISSUE TITLE
wish: Allow titles to customizable (or move label to the end)

### ISSUE THREAD

**Issue by markstos** [jtyers/qutebrowser-profile#13]
`qutebrowser-profile` currently prefixes Qute's window titles with "qute [$profile]". If you have several tabbed windows open in a collection in i3 or Sway, instead of seeing the most useful part-- the unique page title, all that's left is every title is "qute [$profile]". That's not useful since every title now looks likes the same.

<checks>

As it turns out, this feature request is already addressed by PR #12. Here's how it resolves the issue.

The prefix is current set when qutebrowser makes a hardcoded call to use `--set` to set the window title.  But #12 adds support for adding additional `--set` calls which follow this. You can see from this manual test that Qute allows using two `--set` calls to set the title, with the second one "winning". 

      qutebrowser -T --set window.title_format "FIRST {current_title}" --set window.title_format "{current_title} SECOND"

So if you want to move the profile title to the end and customize it, after #12 is merged, you could do this:

    qutebrowser-profile --new work --set window.title_format "{perc} {current_title}{title_sep}[work]"

In the interest of keeping `qutebrowser-profile` simple, I think this may be best resolved with a doc-patch that provides an example like the above. 

Again, this only works when the profiles are launched through `.desktop` files, because that's where the custom command lines are stored.

**Comment by jtyers** [comment]
Apologies for the slow response. Yes I agree with your suggestion that we need this to be customisable. The script, in its new Pythonic form, passes unrecognised args to `qutebrowser` when it is launched, which means your suggestion above now works:

`qutebrowser-profile --load work --new --set window.title_format "{perc} {current_title}{title_sep}[work]"`

I'll close for now as I believe this is fixed but re-open @markstos if you believe otherwise
